//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilaCocheras.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCocheraDTO", Namespace="http://tempuri.org/", ItemName="cocheraDTO")]
    [System.SerializableAttribute()]
    public class ArrayOfCocheraDTO : System.Collections.Generic.List<AlquilaCocheras.ServiceReference.cocheraDTO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cocheraDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class cocheraDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCocheraField;
        
        private int IdPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private double LatitudField;
        
        private double LongitudField;
        
        private double MetrosCuadradosField;
        
        private int TipoVehiculoField;
        
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        private double PuntuacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCochera {
            get {
                return this.IdCocheraField;
            }
            set {
                if ((this.IdCocheraField.Equals(value) != true)) {
                    this.IdCocheraField = value;
                    this.RaisePropertyChanged("IdCochera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPropietario {
            get {
                return this.IdPropietarioField;
            }
            set {
                if ((this.IdPropietarioField.Equals(value) != true)) {
                    this.IdPropietarioField = value;
                    this.RaisePropertyChanged("IdPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((this.PerfilField.Equals(value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double MetrosCuadrados {
            get {
                return this.MetrosCuadradosField;
            }
            set {
                if ((this.MetrosCuadradosField.Equals(value) != true)) {
                    this.MetrosCuadradosField = value;
                    this.RaisePropertyChanged("MetrosCuadrados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int TipoVehiculo {
            get {
                return this.TipoVehiculoField;
            }
            set {
                if ((this.TipoVehiculoField.Equals(value) != true)) {
                    this.TipoVehiculoField = value;
                    this.RaisePropertyChanged("TipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((this.PuntuacionField.Equals(value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.CocherasSoap")]
    public interface CocherasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ubicacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCocheras", ReplyAction="*")]
        AlquilaCocheras.ServiceReference.ObtenerCocherasResponse ObtenerCocheras(AlquilaCocheras.ServiceReference.ObtenerCocherasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCocheras", ReplyAction="*")]
        System.Threading.Tasks.Task<AlquilaCocheras.ServiceReference.ObtenerCocherasResponse> ObtenerCocherasAsync(AlquilaCocheras.ServiceReference.ObtenerCocherasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCocherasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCocheras", Namespace="http://tempuri.org/", Order=0)]
        public AlquilaCocheras.ServiceReference.ObtenerCocherasRequestBody Body;
        
        public ObtenerCocherasRequest() {
        }
        
        public ObtenerCocherasRequest(AlquilaCocheras.ServiceReference.ObtenerCocherasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCocherasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ubicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaFin;
        
        public ObtenerCocherasRequestBody() {
        }
        
        public ObtenerCocherasRequestBody(string ubicacion, System.DateTime fechaInicio, System.DateTime fechaFin) {
            this.ubicacion = ubicacion;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCocherasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCocherasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AlquilaCocheras.ServiceReference.ObtenerCocherasResponseBody Body;
        
        public ObtenerCocherasResponse() {
        }
        
        public ObtenerCocherasResponse(AlquilaCocheras.ServiceReference.ObtenerCocherasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCocherasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlquilaCocheras.ServiceReference.ArrayOfCocheraDTO ObtenerCocherasResult;
        
        public ObtenerCocherasResponseBody() {
        }
        
        public ObtenerCocherasResponseBody(AlquilaCocheras.ServiceReference.ArrayOfCocheraDTO ObtenerCocherasResult) {
            this.ObtenerCocherasResult = ObtenerCocherasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CocherasSoapChannel : AlquilaCocheras.ServiceReference.CocherasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CocherasSoapClient : System.ServiceModel.ClientBase<AlquilaCocheras.ServiceReference.CocherasSoap>, AlquilaCocheras.ServiceReference.CocherasSoap {
        
        public CocherasSoapClient() {
        }
        
        public CocherasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CocherasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CocherasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CocherasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlquilaCocheras.ServiceReference.ObtenerCocherasResponse AlquilaCocheras.ServiceReference.CocherasSoap.ObtenerCocheras(AlquilaCocheras.ServiceReference.ObtenerCocherasRequest request) {
            return base.Channel.ObtenerCocheras(request);
        }
        
        public AlquilaCocheras.ServiceReference.ArrayOfCocheraDTO ObtenerCocheras(string ubicacion, System.DateTime fechaInicio, System.DateTime fechaFin) {
            AlquilaCocheras.ServiceReference.ObtenerCocherasRequest inValue = new AlquilaCocheras.ServiceReference.ObtenerCocherasRequest();
            inValue.Body = new AlquilaCocheras.ServiceReference.ObtenerCocherasRequestBody();
            inValue.Body.ubicacion = ubicacion;
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            AlquilaCocheras.ServiceReference.ObtenerCocherasResponse retVal = ((AlquilaCocheras.ServiceReference.CocherasSoap)(this)).ObtenerCocheras(inValue);
            return retVal.Body.ObtenerCocherasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AlquilaCocheras.ServiceReference.ObtenerCocherasResponse> AlquilaCocheras.ServiceReference.CocherasSoap.ObtenerCocherasAsync(AlquilaCocheras.ServiceReference.ObtenerCocherasRequest request) {
            return base.Channel.ObtenerCocherasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlquilaCocheras.ServiceReference.ObtenerCocherasResponse> ObtenerCocherasAsync(string ubicacion, System.DateTime fechaInicio, System.DateTime fechaFin) {
            AlquilaCocheras.ServiceReference.ObtenerCocherasRequest inValue = new AlquilaCocheras.ServiceReference.ObtenerCocherasRequest();
            inValue.Body = new AlquilaCocheras.ServiceReference.ObtenerCocherasRequestBody();
            inValue.Body.ubicacion = ubicacion;
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            return ((AlquilaCocheras.ServiceReference.CocherasSoap)(this)).ObtenerCocherasAsync(inValue);
        }
    }
}
